[versions]
# libraries
annotations = "24.1.0"
javafx = "22.0.1"

# plugins
kotlin = "2.0.0"
changelog = "2.2.1"
gradleIntelliJPlugin = "1.17.4"
qodana = "2024.1.5"
kover = "0.8.3"
javafxplugin = "0.1.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
javafxBase = { group = "org.openjfx", name = "javafx", version.ref = "javafx" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
javafxPlugin = { id = "org.openjfx.javafxplugin", version.ref = "javafxplugin" }
